#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
wmname LG3D

#BSPWM configuration
## bspc config border_radius        100
#bspc config border_width         1
#bspc config window_gap           3
#bspc config top_padding          25
#bspc config bottom_padding       3
#bspc config left_padding         3
#bspc config right_padding        3
#bspc config single_monocle       false
##bspc config click_to_focus       true
#bspc config split_ratio          0.50
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
##bspc config focus_by_distance    true
#bspc config focus_follows_pointer true
##bspc config history_aware_focus  true
#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner
#bspc config remove_disabled_monitors true
#bspc config merge_overlapping_monitors true
#
##BSPWM coloring
#bspc config normal_border_color		"#4c566a"
#bspc config active_border_color		"#1e1e1e"
#bspc config focused_border_color	"#5e81ac"
#bspc config presel_feedback_color	"#5e81ac"
##bspc config urgent_border_color 	"#dd2727"
bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          7
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a netease-cloud-music desktop='^6'


#hidden - Is hidden and doesn’t occupy any tiling space.
#sticky - Stays in the focused desktop of its monitor.
#private - Tries to keep the same tiling position/size.
#locked - Ignores the node --close message.
#marked - Is marked (useful for deferred actions). A marked node becomes unmarked after being sent on a preselected node.
#center - Center window if state=floating.
#follow - Change to monitor/desktop of window.
#manage - Window is managed. An unmanaged window is not part of the tree.
#focus - Focus the window.
#border - Visibility of the window border.
