#!/usr/bin/env sh
#
# wm independent hotkeys
#

# terminal emulator
super + Return
	xfce4-terminal
# termianl emulator south
super + alt + Return
	bspc node -p south && xfce4-terminal

# termianl emulator north
alt + Return
	bspc node -p north && xfce4-terminal

# termianl emulator west
ctrl + Return
	bspc node -p west && xfce4-terminal

# termianl emulator east
super + ctrl + Return
	bspc node -p east && xfce4-terminal

# program launcher
super + alt + @space
	dmenu_run
super + @space
  rofi -combi-modi window,drun,ssh -theme solarized -font "hack 10" -show combi

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + { q, r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + } w
	bspc node -{c,k}

# focus the last node/desktop
super + { grave, Tab}
	bspc {node,desktop} -f last

# focus the next/previous desktop in the current monitor
super + bracket{ left, right}
	bspc desktop -f {prev,next}.local
# alternate between the tiled and monocle layout

super + m
	bspc desktop -l next

# focus the next/previous window in the current desktop
super + {_,shift + } c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous window in the current desktop
super + {_,shift + } x
	bspc node -f {next,prev}.local.floating.!hidden.window

super + {_,shift + } Tab
	bspc node -f {next,prev}.local.fullscreen.!hidden.window

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the window state
super + shift + s
	bspc node -t tiled

# set the window state
super + shift + f
	bspc node -t tiled

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

super + z
  bspc node -f biggest.local && bspc node -f last && bspc node -s last

super + shift +z
  bspc node -f smallest.local&& bspc node last -s focused
#
alt + z
  bspc node -f biggest.local
alt + shift +z
  bspc node -f smallest.local


# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}


# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# my hotkeys
super + a
  bspc node first_ancestor -F horizontal
super + shift + a
  bspc node first_ancestor -F vertical

super + q
  bspc node first_ancestor -R 90
super + shift + q
  bspc node first_ancestor -R -90

alt + a
	alacritty
ctrl + alt + s
	chromium
ctrl + alt + d
	linedict
ctrl + alt + x 
	code $HOME/.config/sxhkd/sxhkdrc
ctrl + alt + a
	flameshot gui
ctrl + alt + m
	netease-cloud-music

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

